# Stage 1: Build React Production Bundle
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files from current directory
COPY package*.json ./
RUN npm install
RUN npm ci

# Copy rest of the frontend source code
COPY . .
RUN npm run build

# Stage 2: Serve using Nginx Alpine
FROM nginx:alpine

# Copy built static files to Nginx web root
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]